using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LogForge.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class PartitionedLogStorage : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
        ALTER TABLE log RENAME TO log_legacy;
        ALTER TABLE log_legacy DROP CONSTRAINT "PK_log";

        CREATE TABLE log (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
            "Timestamp" timestamptz NOT NULL,
            "Level" varchar(5) NOT NULL,
            "Service" text NOT NULL,
            "Message" text NOT NULL,
            "Attributes" jsonb NOT NULL DEFAULT '{}'::jsonb,
            CONSTRAINT "PK_log" PRIMARY KEY ("Timestamp", "Id")
        ) PARTITION BY RANGE ("Timestamp");

        CREATE TABLE log_default PARTITION OF log DEFAULT;

        DO $$
        DECLARE
            partition_day date;
        BEGIN
            FOR partition_day IN
                SELECT generate_series(
                    CURRENT_DATE - 90,
                    CURRENT_DATE + 30,
                    interval '1 day'
                )::date
            LOOP
                EXECUTE format(
                    'CREATE TABLE log_%s PARTITION OF log
                     FOR VALUES FROM (%L) TO (%L)',
                    to_char(partition_day, 'YYYYMMDD'),
                    partition_day,
                    partition_day + 1
                );
            END LOOP;
        END $$;

        INSERT INTO log (
            "Id", "Timestamp", "Level", "Service", "Message", "Attributes"
        )
        SELECT
            "Id",
            "Timestamp",
            "Level",
            "Service",
            "Message",
            COALESCE("Attributes", '{}'::jsonb)
        FROM log_legacy;

        SELECT setval(
            pg_get_serial_sequence('log', 'Id'),
            COALESCE((SELECT MAX("Id") FROM log), 1),
            true
        );

        DROP TABLE log_legacy;

        CREATE INDEX ix_log_timestamp_id
            ON log ("Timestamp" DESC, "Id" DESC);

        CREATE INDEX ix_log_service_timestamp
            ON log ("Service", "Timestamp" DESC);

        CREATE INDEX ix_log_level_timestamp
            ON log ("Level", "Timestamp" DESC);

        CREATE INDEX ix_log_attributes
            ON log USING gin ("Attributes" jsonb_path_ops);
        """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_log",
                table: "log");

            migrationBuilder.AlterColumn<Dictionary<string, object>>(
                name: "Attributes",
                table: "log",
                type: "jsonb",
                nullable: true,
                oldClrType: typeof(Dictionary<string, object>),
                oldType: "jsonb",
                oldDefaultValueSql: "'{}'::jsonb");

            migrationBuilder.AddPrimaryKey(
                name: "PK_log",
                table: "log",
                column: "Id");
        }
    }
}
