using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LogForge.Infrastructure.Migrations;

[DbContext(typeof(LogForge.Infrastructure.Persistence.LogForgeDbContext))]
[Migration("20260819180957_PartitionedLogStorage")]
public partial class PartitionedLogStorage : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            ALTER TABLE log RENAME TO log_legacy;
            ALTER TABLE log_legacy DROP CONSTRAINT "PK_log";

            CREATE TABLE log (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                "Timestamp" timestamptz NOT NULL,
                "Level" varchar(5) NOT NULL,
                "Service" text NOT NULL,
                "Message" text NOT NULL,
                "Attributes" jsonb NOT NULL DEFAULT '{}'::jsonb,
                CONSTRAINT "PK_log" PRIMARY KEY ("Timestamp", "Id")
            ) PARTITION BY RANGE ("Timestamp");

            CREATE TABLE log_default PARTITION OF log DEFAULT;

            DO $$
            DECLARE
                partition_day date;
            BEGIN
                FOR partition_day IN
                    SELECT generate_series(
                        CURRENT_DATE - 5,
                        CURRENT_DATE + 30,
                        interval '1 day'
                    )::date
                LOOP
                    EXECUTE format(
                        'CREATE TABLE log_%s PARTITION OF log
                         FOR VALUES FROM (%L) TO (%L)',
                        to_char(partition_day, 'YYYYMMDD'),
                        partition_day,
                        partition_day + 1
                    );
                END LOOP;
            END $$;

            INSERT INTO log (
                "Id", "Timestamp", "Level", "Service", "Message", "Attributes"
            )
            SELECT
                "Id",
                "Timestamp",
                "Level",
                "Service",
                "Message",
                COALESCE("Attributes", '{}'::jsonb)
            FROM log_legacy;

            SELECT setval(
                pg_get_serial_sequence('log', 'Id'),
                COALESCE((SELECT MAX("Id") FROM log), 1),
                true
            );

            DROP TABLE log_legacy;

            CREATE INDEX "IX_log_Service_Timestamp_Id"
                ON log ("Service", "Timestamp" DESC, "Id" DESC);

            CREATE INDEX "IX_log_Timestamp"
                ON log USING brin ("Timestamp");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS log CASCADE;");
    }
}